apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-registry
  labels:
    app: jmeter-registry
spec:
  selector:
    matchLabels:
      app: jmeter-registry
  replicas: 1
  template:
    metadata:
      labels:
        app: jmeter-registry
    spec:
      containers:
        - name: jmeter-registry
          image: xuujie/jmeter-registry:latest
          ports:
            - containerPort: 9090

---

apiVersion: v1
kind: Service
metadata:
  name: jmeter-registry-service
spec:
  selector:
    app: jmeter-registry
  ports:
    - name: http
      protocol: TCP
      port: 9090
      targetPort: 9090
  type: LoadBalancer

#---
#
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: jmeter-registry-ingress
#  annotations:
#    ingress.kubernetes.io/rewrite-target: /
#spec:
#  rules:
#    - http:
#        paths:
#          - path: /
#            backend:
#              serviceName: jmeter-registry-service
#              servicePort: 80