apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-grafana
  labels:
    app: jmeter-grafana
spec:
  selector:
    matchLabels:
      app: jmeter-grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: jmeter-grafana
    spec:
      containers:
        - name: jmeter-grafana
          image: grafana/grafana:latest
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: JmeterGrafana123
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: jmeter-grafana-service
spec:
  selector:
    app: jmeter-grafana
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer