version: "3.7"
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - /tmp/volumes/influxdb:/var/lib/influxdb
